package controllers;

import entity.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import repositories.ArticleRepository;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicLong;


@RestController
public class ArticleController {

    private static final String template = "Hello World";
    private final AtomicLong counter = new AtomicLong();

    @GetMapping("/getAll")
    public List<Article> getAllArticles() {

        List<Article> hmap = new ArrayList<Article>();
        Article article = new Article();
        article.setId((long) 1);
        article.setName("RENBERGET");
        article.setDescription("Confortable, léger et facile à déplacer. La forme des accoudoirs ajoute au confort et le mécanisme de freinage des roulettes maintient le fauteuil en place lorsque vous vous levez et le libère lorsque vous vous asseyez.");
        article.setColor("Rouge");
        article.setPrice(40);
        SubCategory subCategory = new SubCategory();
        subCategory.setId((long) 1);
        subCategory.setName("Chaise de bureau");
        Category category = new Category();
        category.setId((long) 1);
        category.setName("Chaises");
        subCategory.setCategory(category);
        ArrayList<SubCategory> listSubCategory = new ArrayList<SubCategory>();
        article.setSubCategories((Set<SubCategory>) listSubCategory);
        ArrayList<Image> listImage = new ArrayList<Image>();
        Image image = new Image();
        image.setId((long) 1);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1020135_pe831794_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 2);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025981_pe834276_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 3);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025978_pe834273_s5.jpg?f=xxs");
        listImage.add(image);
        Rating rating = new Rating();
        rating.setId((long) 1);
        rating.setRating(5);
        ArrayList<Rating> listRating = new ArrayList<Rating>();
        listRating.add(rating);
        rating.setId((long) 2);
        rating.setRating((float) 4.7);
        listRating.add(rating);
        hmap.add(article);

        article.setId((long) 2);
        article.setName("Chaise de bureau");
        article.setDescription("Confortable, léger et facile à déplacer. La forme des accoudoirs ajoute au confort et le mécanisme de freinage des roulettes maintient le fauteuil en place lorsque vous vous levez et le libère lorsque vous vous asseyez.");
        article.setColor("Rouge");
        article.setPrice(40);
        subCategory = new SubCategory();
        subCategory.setId((long) 1);
        subCategory.setName("Chaise de bureau");
        category = new Category();
        category.setId((long) 1);
        category.setName("Chaises");
        subCategory.setCategory(category);
        listSubCategory = new ArrayList<SubCategory>();
        article.setSubCategories((Set<SubCategory>) listSubCategory);
        listImage = new ArrayList<Image>();
        image = new Image();
        image.setId((long) 1);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1020135_pe831794_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 2);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025981_pe834276_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 3);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025978_pe834273_s5.jpg?f=xxs");
        listImage.add(image);
        rating = new Rating();
        rating.setId((long) 1);
        rating.setRating(5);
        listRating = new ArrayList<Rating>();
        listRating.add(rating);
        rating.setId((long) 2);
        rating.setRating((float) 4.7);
        listRating.add(rating);
        hmap.add(article);

        article.setId((long) 3);
        article.setName("Chaise de bureau");
        article.setDescription("Confortable, léger et facile à déplacer. La forme des accoudoirs ajoute au confort et le mécanisme de freinage des roulettes maintient le fauteuil en place lorsque vous vous levez et le libère lorsque vous vous asseyez.");
        article.setColor("Rouge");
        article.setPrice(40);
        subCategory = new SubCategory();
        subCategory.setId((long) 1);
        subCategory.setName("Chaise de bureau");
        category = new Category();
        category.setId((long) 1);
        category.setName("Chaises");
        subCategory.setCategory(category);
        listSubCategory = new ArrayList<SubCategory>();
        article.setSubCategories((Set<SubCategory>) listSubCategory);
        listImage = new ArrayList<Image>();
        image = new Image();
        image.setId((long) 1);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1020135_pe831794_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 2);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025981_pe834276_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 3);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025978_pe834273_s5.jpg?f=xxs");
        listImage.add(image);
        rating = new Rating();
        rating.setId((long) 1);
        rating.setRating(5);
        listRating = new ArrayList<Rating>();
        listRating.add(rating);
        rating.setId((long) 2);
        rating.setRating((float) 4.7);
        listRating.add(rating);
        hmap.add(article);

        article.setId((long) 4);
        article.setName("Chaise de bureau");
        article.setDescription("Confortable, léger et facile à déplacer. La forme des accoudoirs ajoute au confort et le mécanisme de freinage des roulettes maintient le fauteuil en place lorsque vous vous levez et le libère lorsque vous vous asseyez.");
        article.setColor("Rouge");
        article.setPrice(40);
        subCategory = new SubCategory();
        subCategory.setId((long) 1);
        subCategory.setName("Chaise de bureau");
        category = new Category();
        category.setId((long) 1);
        category.setName("Chaises");
        subCategory.setCategory(category);
        listSubCategory = new ArrayList<SubCategory>();
        article.setSubCategories((Set<SubCategory>) listSubCategory);
        listImage = new ArrayList<Image>();
        image = new Image();
        image.setId((long) 1);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1020135_pe831794_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 2);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025981_pe834276_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 3);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025978_pe834273_s5.jpg?f=xxs");
        listImage.add(image);
        rating = new Rating();
        rating.setId((long) 1);
        rating.setRating(5);
        listRating = new ArrayList<Rating>();
        listRating.add(rating);
        rating.setId((long) 2);
        rating.setRating((float) 4.7);
        listRating.add(rating);
        hmap.add(article);

        article.setId((long) 5);
        article.setName("Chaise de bureau");
        article.setDescription("Confortable, léger et facile à déplacer. La forme des accoudoirs ajoute au confort et le mécanisme de freinage des roulettes maintient le fauteuil en place lorsque vous vous levez et le libère lorsque vous vous asseyez.");
        article.setColor("Rouge");
        article.setPrice(40);
        subCategory = new SubCategory();
        subCategory.setId((long) 1);
        subCategory.setName("Chaise de bureau");
        category = new Category();
        category.setId((long) 1);
        category.setName("Chaises");
        subCategory.setCategory(category);
        listSubCategory = new ArrayList<SubCategory>();
        article.setSubCategories((Set<SubCategory>) listSubCategory);
        listImage = new ArrayList<Image>();
        image = new Image();
        image.setId((long) 1);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1020135_pe831794_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 2);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025981_pe834276_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 3);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025978_pe834273_s5.jpg?f=xxs");
        listImage.add(image);
        rating = new Rating();
        rating.setId((long) 1);
        rating.setRating(5);
        listRating = new ArrayList<Rating>();
        listRating.add(rating);
        rating.setId((long) 2);
        rating.setRating((float) 4.7);
        listRating.add(rating);
        hmap.add(article);

        article.setId((long) 6);
        article.setName("Chaise de bureau");
        article.setDescription("Confortable, léger et facile à déplacer. La forme des accoudoirs ajoute au confort et le mécanisme de freinage des roulettes maintient le fauteuil en place lorsque vous vous levez et le libère lorsque vous vous asseyez.");
        article.setColor("Rouge");
        article.setPrice(40);
        subCategory = new SubCategory();
        subCategory.setId((long) 1);
        subCategory.setName("Chaise de bureau");
        category = new Category();
        category.setId((long) 1);
        category.setName("Chaises");
        subCategory.setCategory(category);
        listSubCategory = new ArrayList<SubCategory>();
        article.setSubCategories((Set<SubCategory>) listSubCategory);
        listImage = new ArrayList<Image>();
        image = new Image();
        image.setId((long) 1);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1020135_pe831794_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 2);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025981_pe834276_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 3);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025978_pe834273_s5.jpg?f=xxs");
        listImage.add(image);
        rating = new Rating();
        rating.setId((long) 1);
        rating.setRating(5);
        listRating = new ArrayList<Rating>();
        listRating.add(rating);
        rating.setId((long) 2);
        rating.setRating((float) 4.7);
        listRating.add(rating);
        hmap.add(article);

        article.setId((long) 7);
        article.setName("Chaise de bureau");
        article.setDescription("Confortable, léger et facile à déplacer. La forme des accoudoirs ajoute au confort et le mécanisme de freinage des roulettes maintient le fauteuil en place lorsque vous vous levez et le libère lorsque vous vous asseyez.");
        article.setColor("Rouge");
        article.setPrice(40);
        subCategory = new SubCategory();
        subCategory.setId((long) 1);
        subCategory.setName("Chaise de bureau");
        category = new Category();
        category.setId((long) 1);
        category.setName("Chaises");
        subCategory.setCategory(category);
        listSubCategory = new ArrayList<SubCategory>();
        article.setSubCategories((Set<SubCategory>) listSubCategory);
        listImage = new ArrayList<Image>();
        image = new Image();
        image.setId((long) 1);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1020135_pe831794_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 2);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025981_pe834276_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 3);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025978_pe834273_s5.jpg?f=xxs");
        listImage.add(image);
        rating = new Rating();
        rating.setId((long) 1);
        rating.setRating(5);
        listRating = new ArrayList<Rating>();
        listRating.add(rating);
        rating.setId((long) 2);
        rating.setRating((float) 4.7);
        listRating.add(rating);
        hmap.add(article);

        article.setId((long) 8);
        article.setName("Chaise de bureau");
        article.setDescription("Confortable, léger et facile à déplacer. La forme des accoudoirs ajoute au confort et le mécanisme de freinage des roulettes maintient le fauteuil en place lorsque vous vous levez et le libère lorsque vous vous asseyez.");
        article.setColor("Rouge");
        article.setPrice(40);
        subCategory = new SubCategory();
        subCategory.setId((long) 1);
        subCategory.setName("Chaise de bureau");
        category = new Category();
        category.setId((long) 1);
        category.setName("Chaises");
        subCategory.setCategory(category);
        listSubCategory = new ArrayList<SubCategory>();
        article.setSubCategories((Set<SubCategory>) listSubCategory);
        listImage = new ArrayList<Image>();
        image = new Image();
        image.setId((long) 1);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1020135_pe831794_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 2);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025981_pe834276_s5.jpg?f=xxs");
        listImage.add(image);
        image.setId((long) 3);
        image.setUrl("https://www.ikea.com/fr/fr/images/products/renberget-chaise-pivotante-bomstad-noir__1025978_pe834273_s5.jpg?f=xxs");
        listImage.add(image);
        rating = new Rating();
        rating.setId((long) 1);
        rating.setRating(5);
        listRating = new ArrayList<Rating>();
        listRating.add(rating);
        rating.setId((long) 2);
        rating.setRating((float) 4.7);
        listRating.add(rating);
        hmap.add(article);

        return hmap;
    }
}
